services:
  - type: web
    name: colabwize-backend
    env: node
    buildCommand: "npm install --production=false"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production